server:
  port: 8001
spring:
  application:
    name: springcloud-comsumer-service
cache:
  service:
    config: 1122222
    enable: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka